name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  who-to-greet:  # id of input
    description: 'Who to greet'
    required: true
    default: 'World'

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: save aws ecr image scan results to file
      run: |
        echo "{\"imageScanFindings\": {\"findings\": [{\"name\": \"CVE-2019-8457\",\"description\": \"SQLite3 from 3.6.0 to and including 3.27.2 is vulnerable to heap out-of-bound read in the rtreenode() function when handling invalid rtree tables.\",\"uri\": \"https://security-tracker.debian.org/tracker/CVE-2019-8457\",\"severity\": \"HIGH\",\"attributes\": [{\"key\": \"package_version\",\"value\": \"5.3.28+dfsg1-0.8\"},{\"key\": \"package_name\",\"value\": \"db5.3\"},{\"key\": \"CVSS2_VECTOR\",\"value\": \"AV:N/AC:L/Au:N/C:P/I:P/A:P\"},{\"key\": \"CVSS2_SCORE\",\"value\": \"7.5\"}]},{\"name\": \"CVE-2022-1304\",\"description\": \"An out-of-bounds read/write vulnerability was found in e2fsprogs 1.46.5. This issue leads to a segmentation fault and possibly arbitrary code execution via a specially crafted filesystem.\",\"uri\": \"https://security-tracker.debian.org/tracker/CVE-2022-1304\",\"severity\": \"MEDIUM\",\"attributes\": [{\"key\": \"package_version\",\"value\": \"1.46.2-2\"},{\"key\": \"package_name\",\"value\": \"e2fsprogs\"},{\"key\": \"CVSS2_VECTOR\",\"value\": \"AV:N/AC:M/Au:N/C:P/I:P/A:P\"},{\"key\": \"CVSS2_SCORE\",\"value\": \"6.8\"}]}],\"imageScanCompletedAt\": \"2022-10-24T15:41:23+00:00\",\"vulnerabilitySourceUpdatedAt\": \"2022-10-24T06:42:54+00:00\",\"findingSeverityCounts\": {\"HIGH\": 1,\"MEDIUM\": 5,\"LOW\": 5,\"INFORMATIONAL\": 29}},\"registryId\": \"433273847185\",\"repositoryName\": \"dfx-api\",\"imageId\": {\"imageDigest\": \"sha256:4725b986d69df844a4e549f39f47d73589deb429144b96d915ab9abde7f7aa8e\"},\"imageScanStatus\": {\"status\": \"COMPLETE\",\"description\": \"The scan was completed successfully.\"}}" >> ecr-output.json
      shell: bash
    - name: Upload ecr scan results
      uses: actions/upload-artifact@v2
      with:
        name: ecr-scan-results
        path: ecr-output.json
